// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/formbricks-rewrite/apps/store/internal/ent/experiencedata"
	"github.com/formbricks/formbricks-rewrite/apps/store/internal/ent/predicate"
)

// ExperienceDataDelete is the builder for deleting a ExperienceData entity.
type ExperienceDataDelete struct {
	config
	hooks    []Hook
	mutation *ExperienceDataMutation
}

// Where appends a list predicates to the ExperienceDataDelete builder.
func (edd *ExperienceDataDelete) Where(ps ...predicate.ExperienceData) *ExperienceDataDelete {
	edd.mutation.Where(ps...)
	return edd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (edd *ExperienceDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, edd.sqlExec, edd.mutation, edd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (edd *ExperienceDataDelete) ExecX(ctx context.Context) int {
	n, err := edd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (edd *ExperienceDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(experiencedata.Table, sqlgraph.NewFieldSpec(experiencedata.FieldID, field.TypeUUID))
	if ps := edd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, edd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	edd.mutation.done = true
	return affected, err
}

// ExperienceDataDeleteOne is the builder for deleting a single ExperienceData entity.
type ExperienceDataDeleteOne struct {
	edd *ExperienceDataDelete
}

// Where appends a list predicates to the ExperienceDataDelete builder.
func (eddo *ExperienceDataDeleteOne) Where(ps ...predicate.ExperienceData) *ExperienceDataDeleteOne {
	eddo.edd.mutation.Where(ps...)
	return eddo
}

// Exec executes the deletion query.
func (eddo *ExperienceDataDeleteOne) Exec(ctx context.Context) error {
	n, err := eddo.edd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{experiencedata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eddo *ExperienceDataDeleteOne) ExecX(ctx context.Context) {
	if err := eddo.Exec(ctx); err != nil {
		panic(err)
	}
}
