// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/formbricks-rewrite/apps/hub/internal/ent/enrichmentjob"
	"github.com/formbricks/formbricks-rewrite/apps/hub/internal/ent/experiencedata"
	"github.com/formbricks/formbricks-rewrite/apps/hub/internal/ent/predicate"
	"github.com/google/uuid"
)

// EnrichmentJobQuery is the builder for querying EnrichmentJob entities.
type EnrichmentJobQuery struct {
	config
	ctx            *QueryContext
	order          []enrichmentjob.OrderOption
	inters         []Interceptor
	predicates     []predicate.EnrichmentJob
	withExperience *ExperienceDataQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EnrichmentJobQuery builder.
func (ejq *EnrichmentJobQuery) Where(ps ...predicate.EnrichmentJob) *EnrichmentJobQuery {
	ejq.predicates = append(ejq.predicates, ps...)
	return ejq
}

// Limit the number of records to be returned by this query.
func (ejq *EnrichmentJobQuery) Limit(limit int) *EnrichmentJobQuery {
	ejq.ctx.Limit = &limit
	return ejq
}

// Offset to start from.
func (ejq *EnrichmentJobQuery) Offset(offset int) *EnrichmentJobQuery {
	ejq.ctx.Offset = &offset
	return ejq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ejq *EnrichmentJobQuery) Unique(unique bool) *EnrichmentJobQuery {
	ejq.ctx.Unique = &unique
	return ejq
}

// Order specifies how the records should be ordered.
func (ejq *EnrichmentJobQuery) Order(o ...enrichmentjob.OrderOption) *EnrichmentJobQuery {
	ejq.order = append(ejq.order, o...)
	return ejq
}

// QueryExperience chains the current query on the "experience" edge.
func (ejq *EnrichmentJobQuery) QueryExperience() *ExperienceDataQuery {
	query := (&ExperienceDataClient{config: ejq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ejq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ejq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enrichmentjob.Table, enrichmentjob.FieldID, selector),
			sqlgraph.To(experiencedata.Table, experiencedata.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, enrichmentjob.ExperienceTable, enrichmentjob.ExperienceColumn),
		)
		fromU = sqlgraph.SetNeighbors(ejq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EnrichmentJob entity from the query.
// Returns a *NotFoundError when no EnrichmentJob was found.
func (ejq *EnrichmentJobQuery) First(ctx context.Context) (*EnrichmentJob, error) {
	nodes, err := ejq.Limit(1).All(setContextOp(ctx, ejq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enrichmentjob.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) FirstX(ctx context.Context) *EnrichmentJob {
	node, err := ejq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EnrichmentJob ID from the query.
// Returns a *NotFoundError when no EnrichmentJob ID was found.
func (ejq *EnrichmentJobQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ejq.Limit(1).IDs(setContextOp(ctx, ejq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{enrichmentjob.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ejq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EnrichmentJob entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EnrichmentJob entity is found.
// Returns a *NotFoundError when no EnrichmentJob entities are found.
func (ejq *EnrichmentJobQuery) Only(ctx context.Context) (*EnrichmentJob, error) {
	nodes, err := ejq.Limit(2).All(setContextOp(ctx, ejq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enrichmentjob.Label}
	default:
		return nil, &NotSingularError{enrichmentjob.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) OnlyX(ctx context.Context) *EnrichmentJob {
	node, err := ejq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EnrichmentJob ID in the query.
// Returns a *NotSingularError when more than one EnrichmentJob ID is found.
// Returns a *NotFoundError when no entities are found.
func (ejq *EnrichmentJobQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ejq.Limit(2).IDs(setContextOp(ctx, ejq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{enrichmentjob.Label}
	default:
		err = &NotSingularError{enrichmentjob.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ejq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EnrichmentJobs.
func (ejq *EnrichmentJobQuery) All(ctx context.Context) ([]*EnrichmentJob, error) {
	ctx = setContextOp(ctx, ejq.ctx, ent.OpQueryAll)
	if err := ejq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EnrichmentJob, *EnrichmentJobQuery]()
	return withInterceptors[[]*EnrichmentJob](ctx, ejq, qr, ejq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) AllX(ctx context.Context) []*EnrichmentJob {
	nodes, err := ejq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EnrichmentJob IDs.
func (ejq *EnrichmentJobQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ejq.ctx.Unique == nil && ejq.path != nil {
		ejq.Unique(true)
	}
	ctx = setContextOp(ctx, ejq.ctx, ent.OpQueryIDs)
	if err = ejq.Select(enrichmentjob.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ejq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ejq *EnrichmentJobQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ejq.ctx, ent.OpQueryCount)
	if err := ejq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ejq, querierCount[*EnrichmentJobQuery](), ejq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) CountX(ctx context.Context) int {
	count, err := ejq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ejq *EnrichmentJobQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ejq.ctx, ent.OpQueryExist)
	switch _, err := ejq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ejq *EnrichmentJobQuery) ExistX(ctx context.Context) bool {
	exist, err := ejq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EnrichmentJobQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ejq *EnrichmentJobQuery) Clone() *EnrichmentJobQuery {
	if ejq == nil {
		return nil
	}
	return &EnrichmentJobQuery{
		config:         ejq.config,
		ctx:            ejq.ctx.Clone(),
		order:          append([]enrichmentjob.OrderOption{}, ejq.order...),
		inters:         append([]Interceptor{}, ejq.inters...),
		predicates:     append([]predicate.EnrichmentJob{}, ejq.predicates...),
		withExperience: ejq.withExperience.Clone(),
		// clone intermediate query.
		sql:  ejq.sql.Clone(),
		path: ejq.path,
	}
}

// WithExperience tells the query-builder to eager-load the nodes that are connected to
// the "experience" edge. The optional arguments are used to configure the query builder of the edge.
func (ejq *EnrichmentJobQuery) WithExperience(opts ...func(*ExperienceDataQuery)) *EnrichmentJobQuery {
	query := (&ExperienceDataClient{config: ejq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ejq.withExperience = query
	return ejq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ExperienceID uuid.UUID `json:"experience_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EnrichmentJob.Query().
//		GroupBy(enrichmentjob.FieldExperienceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ejq *EnrichmentJobQuery) GroupBy(field string, fields ...string) *EnrichmentJobGroupBy {
	ejq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EnrichmentJobGroupBy{build: ejq}
	grbuild.flds = &ejq.ctx.Fields
	grbuild.label = enrichmentjob.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ExperienceID uuid.UUID `json:"experience_id,omitempty"`
//	}
//
//	client.EnrichmentJob.Query().
//		Select(enrichmentjob.FieldExperienceID).
//		Scan(ctx, &v)
func (ejq *EnrichmentJobQuery) Select(fields ...string) *EnrichmentJobSelect {
	ejq.ctx.Fields = append(ejq.ctx.Fields, fields...)
	sbuild := &EnrichmentJobSelect{EnrichmentJobQuery: ejq}
	sbuild.label = enrichmentjob.Label
	sbuild.flds, sbuild.scan = &ejq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EnrichmentJobSelect configured with the given aggregations.
func (ejq *EnrichmentJobQuery) Aggregate(fns ...AggregateFunc) *EnrichmentJobSelect {
	return ejq.Select().Aggregate(fns...)
}

func (ejq *EnrichmentJobQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ejq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ejq); err != nil {
				return err
			}
		}
	}
	for _, f := range ejq.ctx.Fields {
		if !enrichmentjob.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ejq.path != nil {
		prev, err := ejq.path(ctx)
		if err != nil {
			return err
		}
		ejq.sql = prev
	}
	return nil
}

func (ejq *EnrichmentJobQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EnrichmentJob, error) {
	var (
		nodes       = []*EnrichmentJob{}
		_spec       = ejq.querySpec()
		loadedTypes = [1]bool{
			ejq.withExperience != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EnrichmentJob).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EnrichmentJob{config: ejq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ejq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ejq.withExperience; query != nil {
		if err := ejq.loadExperience(ctx, query, nodes, nil,
			func(n *EnrichmentJob, e *ExperienceData) { n.Edges.Experience = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ejq *EnrichmentJobQuery) loadExperience(ctx context.Context, query *ExperienceDataQuery, nodes []*EnrichmentJob, init func(*EnrichmentJob), assign func(*EnrichmentJob, *ExperienceData)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*EnrichmentJob)
	for i := range nodes {
		fk := nodes[i].ExperienceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(experiencedata.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "experience_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ejq *EnrichmentJobQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ejq.querySpec()
	_spec.Node.Columns = ejq.ctx.Fields
	if len(ejq.ctx.Fields) > 0 {
		_spec.Unique = ejq.ctx.Unique != nil && *ejq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ejq.driver, _spec)
}

func (ejq *EnrichmentJobQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(enrichmentjob.Table, enrichmentjob.Columns, sqlgraph.NewFieldSpec(enrichmentjob.FieldID, field.TypeUUID))
	_spec.From = ejq.sql
	if unique := ejq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ejq.path != nil {
		_spec.Unique = true
	}
	if fields := ejq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enrichmentjob.FieldID)
		for i := range fields {
			if fields[i] != enrichmentjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ejq.withExperience != nil {
			_spec.Node.AddColumnOnce(enrichmentjob.FieldExperienceID)
		}
	}
	if ps := ejq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ejq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ejq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ejq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ejq *EnrichmentJobQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ejq.driver.Dialect())
	t1 := builder.Table(enrichmentjob.Table)
	columns := ejq.ctx.Fields
	if len(columns) == 0 {
		columns = enrichmentjob.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ejq.sql != nil {
		selector = ejq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ejq.ctx.Unique != nil && *ejq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ejq.predicates {
		p(selector)
	}
	for _, p := range ejq.order {
		p(selector)
	}
	if offset := ejq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ejq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EnrichmentJobGroupBy is the group-by builder for EnrichmentJob entities.
type EnrichmentJobGroupBy struct {
	selector
	build *EnrichmentJobQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ejgb *EnrichmentJobGroupBy) Aggregate(fns ...AggregateFunc) *EnrichmentJobGroupBy {
	ejgb.fns = append(ejgb.fns, fns...)
	return ejgb
}

// Scan applies the selector query and scans the result into the given value.
func (ejgb *EnrichmentJobGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ejgb.build.ctx, ent.OpQueryGroupBy)
	if err := ejgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EnrichmentJobQuery, *EnrichmentJobGroupBy](ctx, ejgb.build, ejgb, ejgb.build.inters, v)
}

func (ejgb *EnrichmentJobGroupBy) sqlScan(ctx context.Context, root *EnrichmentJobQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ejgb.fns))
	for _, fn := range ejgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ejgb.flds)+len(ejgb.fns))
		for _, f := range *ejgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ejgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ejgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EnrichmentJobSelect is the builder for selecting fields of EnrichmentJob entities.
type EnrichmentJobSelect struct {
	*EnrichmentJobQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ejs *EnrichmentJobSelect) Aggregate(fns ...AggregateFunc) *EnrichmentJobSelect {
	ejs.fns = append(ejs.fns, fns...)
	return ejs
}

// Scan applies the selector query and scans the result into the given value.
func (ejs *EnrichmentJobSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ejs.ctx, ent.OpQuerySelect)
	if err := ejs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EnrichmentJobQuery, *EnrichmentJobSelect](ctx, ejs.EnrichmentJobQuery, ejs, ejs.inters, v)
}

func (ejs *EnrichmentJobSelect) sqlScan(ctx context.Context, root *EnrichmentJobQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ejs.fns))
	for _, fn := range ejs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ejs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ejs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
