// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EnrichmentJob is the predicate function for enrichmentjob builders.
type EnrichmentJob func(*sql.Selector)

// ExperienceData is the predicate function for experiencedata builders.
type ExperienceData func(*sql.Selector)
